modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "AGPL-3.0+ALEC"

[[mods]]
modId = "anvillib"
version = "${version}"
displayName = "AnvilLib"
authors = "LordMZTE, (tilera)"
description = '''
AnvilLib library mod
'''
#logoFile = ""

[[dependencies.anvillib]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.anvillib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.anvillib]]
modId = "geckolib3"
mandatory = true
versionRange = "[3.0.57,)"
ordering = "NONE"
side = "BOTH"

