modLoader = "javafml"
loaderVersion = "[40,)"
license = "AGPL-3.0+ALEC"

issueTrackerURL = "https://git.tilera.org/Anvilcraft/anvillib/issues"

[[mods]]
modId = "anvillib"
version = "${version}"
displayName = "anvillib"
displayURL = "https://anvilcraft.net/"
#credits = ""
authors = "LordMZTE, (tilera)"

description = '''
Core for Notex 4.

Includes recipes and tweaks.
'''

[[dependencies.anvillib]]
modId = "forge"
mandatory = true

versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.anvillib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.anvillib]]
modId = "geckolib3"
mandatory = true
versionRange = "[3.0.57,)"
ordering = "NONE"
side = "BOTH"
