modLoader = "javafml"
loaderVersion = "[1,)"
license = "AGPL-3.0+ALEC"

[[mods]]
modId = "anvillib"
version = "${version}"
displayName = "AnvilLib"
authors = "LordMZTE, tilera"
description = '''
AnvilLib library mod
'''

[[dependencies.anvillib]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.anvillib]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.anvillib]]
modId = "geckolib"
type = "optional"
versionRange = "[4.5,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "anvillib-common.mixins.json"

[[mixins]]
config = "anvillib.mixins.json"
